config/routes.rb
Quicktag::Application.routes.draw do
  resources :quick_tags

  resources :tags

  resources :users
  

  root :to => "home#index"
  
  match "/auth/:provider/callback" => "sessions#create"
  
  match "/signout" => "sessions#destroy", :as => :signout
  
  match "/new_quicktag" => "tags#quicktag"
  
  match "/tags_day" => "tags#tagsday"
  
  match "/help" => "help#index"
  
  match "/week" => "tags#week"
  
  match "/admin" => "admin#index"
  match "/admin/users" => "admin#users"
  match "/admin/tags" => "admin#tags"
  
  match "/experiments" => "tags#experiments"
  match "/conduct" => "tags#conduct"
  
  resources :tags do
  	get :autocomplete_title, :on => :collection
  end
  
  

end

app/views/admin/index.html.erb
<h1> Welcome Vince and Brendan...let's do some admin work!</h1>

<p>View tags for all users: <%= link_to "Show me the Tags", "/admin/tags" %></p>

<p>View all users: <%= link_to "Users 'r us", "/admin/users" %></p>

<%= link_to "Return to home page!", root_url %>

app/views/admin/tags.html.erb
   
<h1>Listing tags</h1>
<%= link_to 'Back', admin_path %>
<table>
  <tr>
  	<th>id</th>
    <th>Time</th>
    <th>Title</th>
    <th>Notes</th>
    <th>Location</th>
    <th>Date</th>
    <th>User ID</th>
    <th>Created At</th>
    <th>Updated At</th>
  </tr>
	
<% @tags.each do |tag| %>
  <tr>
  	<td><%= tag.id %></td>
    <td><%= tag.time %></td>
    <td><%= tag.title %></td>
    <td><%= tag.notes %></td>
    <td><%= tag.date %></td>
    <td><%= tag.user_id %></td>
    <td><%= tag.created_at %></td>
    <td><%= tag.updated_at %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
<% end %>
</table>

<br />

app/views/admin/users.html.erb
   
<h1>Listing users</h1>
<%= link_to 'Back', admin_path %>

<table>
  <tr>
  	<th>id</th>
    <th>Username</th>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th>About</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Zip code</th>
    <th>Uid</th>
    <th>Provider</th>
	<th>Time Zone</th>
	<th>Created At</th>
	<th>Updated At</th>
    <th></th>
  </tr>
	
<% @users.each do |user| %>
  <tr>
  	<td><%= user.id %></td>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.about %></td>
    <td><%= user.age %></td>
    <td><%= user.sex %></td>
    <td><%= user.zip_code %></td>
	<td><%= user.uid %></td>
	<td><%= user.provider %></td>
	<td><%= user.time_zone %></td>
	<td><%= user.created_at %></td>
	<td><%= user.updated_at %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
<% end %>
</table>

<br />