config/routes.rb
Quicktag::Application.routes.draw do
  resources :quick_tags

  resources :tags

  resources :users
  

  root :to => "home#index"
  
  match "/auth/:provider/callback" => "sessions#create"
  
  match "/signout" => "sessions#destroy", :as => :signout
  
  match "/new_quicktag" => "tags#quicktag"
  
  match "/tags_day" => "tags#tagsday"
  
  match "/help" => "help#index"
  
  match "/week" => "tags#week"
  
  match "/admin" => "admin#index"
  match "/admin/users" => "admin#users"
  match "/admin/tags" => "admin#tags"
  
  match "/experiments" => "tags#experiments"
  match "/conduct" => "tags#conduct"
  
  resources :tags do
  	get :autocomplete_title, :on => :collection
  end
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :tags
	has_many :quick_tags
	
	#Validation on input
	#validates :age, :numericality => { :only_integer => true, :message => "Please enter your age" }
	#validates :sex, :presence => true
	
	#User name valdation
	validates :username, :uniqueness => true
	
	#Email valdation
	validates :email, :uniqueness => true, :allow_blank => true
	#validates :email, :format => { :with => /\A[a-zA-Z]+\z/,
    #:message => "Only letters allowed" }, :allow_blank => true
	
	
	#Zip code validation
	validates :zip_code, :numericality => { :only_integer => true }, :allow_blank => true
	validates :zip_code, :length => { :is => 5 }, :allow_blank => true
	
	def self.create_with_omniauth(auth)
    	create! do |user|
      		user.provider = auth["provider"]
		    user.uid = auth["uid"]
		    user.first_name = auth["info"]["name"]
			user.username = auth["info"]["username"]
    	end
  	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :authenticate
  
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
	
    respond_to do |format|
      format.html  #show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
  	@title = "Profile"
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(edit_user_path(current_user)) }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(edit_user_path(current_user)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  
  def authenticate
  	authenticate_or_request_with_http_basic do |username, password|
		username == "admin" && password == "admin"
  	end 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about, :rows => 5 %>
  </div>
  
  <%	age_range = ["-"]
  		age_range = age_range.concat((13..99).to_a)
  %>
  
  <div class="field">
    <%= f.label :age %><br />
    <%= f.select :age, age_range %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.select :sex, ["","M","F"] %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select :time_zone %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
    <div id="content">
		<%= form_for(@user) do |f| %>
  			<% if @user.errors.any? %>
    			<div id="error_explanation">
      				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
				</h2>
			    <ul>
      				<% @user.errors.full_messages.each do |msg| %>
      		  			<li>
							<%= msg %>
						</li>
      				<% end %>
      			</ul>
    			</div>
  			<% end %>
    		<div id="interior">
				<fieldset>
					<ul class="pageitem">
						<li class="bigfield">
							<%= f.text_field :username, :placeholder => "Username" %>
						</li>
					</ul>        
					<ul class="pageitem">
						<li class="bigfield">
							<%= f.text_field :first_name, :placeholder => "Name" %>
						</li>
					</ul>
					<ul class="pageitem">
        			    <li class="textbox">
							<%= f.text_area :about, :placeholder => "Bio", :rows => 4 %>
						</li>
					</ul>        
					<ul class="pageitem">
						<li class="bigfield">
							<%= f.text_field :email , :placeholder => "Email Address" %>
						</li>
					</ul>
					<ul class="pageitem">
						<li class="select">
							<span class="arrow"></span> 
							<%= f.select :sex, ["","Male","Female"] %>
						</li>
					</ul>        
        			<ul class="pageitem">
        				<li class="checkbox" style="position:relative">
							<span class="name" style="position:absolute;">Birthday</span>
								<input type="date" id="user_age" name="user[age]" value="<%= current_user.age.to_date %>"></input>
						</li>
					</ul>
										
					<ul class="pageitem">
						<li class="bigfield">
							<%= f.text_field :zip_code, :placeholder => "Zip Code" %>
						</li>
					</ul>            
					<ul class="pageitem">
						<li class="select">
							<span class="arrow"></span> 
							<%= f.time_zone_select :time_zone %>
						</li>
					</ul>   
   					<%= f.hidden_field :uid %>
					<ul class="pageitem">      
						<li class="button">
							<%= f.submit :value => "UPDATE", :class => "orange" %>
						</li>
					</ul>
			</fieldset>
		<% end %>
        </div><!--close interior-->
    </div><!--close content-->

app/views/users/index.html.erb
   
<h1>Listing users</h1>

<table>
  <tr>
  	<th>id</th>
    <th>Username</th>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th>About</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Zip code</th>
    <th>Uid</th>
    <th>Provider</th>
	<th>Time Zone</th>
    <th></th>
  </tr>
	
<% @users.each do |user| %>
  <tr>
  	<td><%= user.id %></td>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.about %></td>
    <td><%= user.age %></td>
    <td><%= user.sex %></td>
    <td><%= user.zip_code %></td>
	<td><%= user.uid %></td>
	<td><%= user.provider %></td>
	<td><%= user.time_zone %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>About:</b>
  <%= @user.about %>
</p>

<p>
  <b>Age:</b>
  <%= @user.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @user.sex %>
</p>

<p>
  <b>Zip code:</b>
  <%= @user.zip_code %>
</p>

<%= @tags %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>