config/routes.rb
Quicktag::Application.routes.draw do
  resources :quick_tags

  resources :tags

  resources :users
  

  root :to => "home#index"
  
  match "/auth/:provider/callback" => "sessions#create"
  
  match "/signout" => "sessions#destroy", :as => :signout
  
  match "/new_quicktag" => "tags#quicktag"
  
  match "/tags_day" => "tags#tagsday"
  
  match "/help" => "help#index"
  
  match "/week" => "tags#week"
  
  match "/admin" => "admin#index"
  match "/admin/users" => "admin#users"
  match "/admin/tags" => "admin#tags"
  
  match "/experiments" => "tags#experiments"
  match "/conduct" => "tags#conduct"
  
  resources :tags do
  	get :autocomplete_title, :on => :collection
  end
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate
  
  def index
  
  end
  
  protected
  
  def authenticate
  	authenticate_or_request_with_http_basic do |username, password|
		username == "admin" && password == "admin"
  	end 
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- Load content into body of application.html.erb -->
	<% if current_user %>

	    <div id="content">
	    	<ul id="nav">
	        	<li class="quick-tags"><a href="<%= quick_tags_path %>">Quick Tags</a></li>
	        	<li class="add-tag"><a href="<%= new_tag_path %>">Add Tag</a></li>
	        	<li class="view-tags"><a href="<%= tags_path %>">View Tags</a></li>
	        	<li class="experiments"><a href="/experiments">Experiments</a></li>
	        	<li class="profile"><a href="<%= edit_user_path(current_user) %>">Profile</a></li>
	        	<li class="help last"><a href="<%= '/help' %>">Help</a></li>
	        </ul>
	    </div><!--close content-->
	<% else %>
	      	<img src="/images/taglab-logo.png" alt="TagLab" style="width: 90%; margin: 0 auto; display: block; padding-top: 40px;" />
	    	<a href="/auth/twitter/"><img src="/images/twitter.png" alt="Sign in with Twitter" style="width: 80%; margin: 0 auto; display:block; margin-top: 80px;" /></a>
	       	<!--<a href=""/auth/facebook/"><img src="/images/facebook.png" alt="Sign in with Facebook" style="width: 80%; margin: 0 auto; display:block; margin-top: 40px;" /></a>-->
	       	<p style="text-align: center; font-size: 10pt; color: #ff6600; padding-top: 100px;">&copy; copyright 2012 Tag Lab</p>
	<% end %>
	


	

	
	



   