config/routes.rb
Quicktag::Application.routes.draw do
  resources :quick_tags

  resources :tags

  resources :users
  

  root :to => "home#index"
  
  match "/auth/:provider/callback" => "sessions#create"
  
  match "/signout" => "sessions#destroy", :as => :signout
  
  match "/new_quicktag" => "tags#quicktag"
  
  match "/tags_day" => "tags#tagsday"
  
  match "/help" => "help#index"
  
  match "/week" => "tags#week"
  
  match "/admin" => "admin#index"
  match "/admin/users" => "admin#users"
  match "/admin/tags" => "admin#tags"
  
  match "/experiments" => "tags#experiments"
  match "/conduct" => "tags#conduct"
  
  resources :tags do
  	get :autocomplete_title, :on => :collection
  end
  
  

end

app/models/quick_tag.rb
class QuickTag < ActiveRecord::Base

	belongs_to :user
	
end

app/controllers/quick_tags_controller.rb
class QuickTagsController < ApplicationController
  # GET /quick_tags
  # GET /quick_tags.xml
  def index
  	@title = "Quick tags"
    @quick_tags = QuickTag.where(:user_id => current_user.id).order("category DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quick_tags }
    end
  end

  # GET /quick_tags/1
  # GET /quick_tags/1.xml
  def show
    @quick_tag = QuickTag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quick_tag }
    end
  end

  # GET /quick_tags/new
  # GET /quick_tags/new.xml
  def new
    @quick_tag = QuickTag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quick_tag }
    end
  end

  # GET /quick_tags/1/edit
  def edit
  	@title = "Edit Quick tag"
    @quick_tag = QuickTag.find(params[:id])
  end

  # POST /quick_tags
  # POST /quick_tags.xml
  def create
    @quick_tag = QuickTag.new(params[:quick_tag])

    respond_to do |format|
      if @quick_tag.save
        format.html { redirect_to(quick_tags_path)}
		#format.html { redirect_to(@quick_tag, :notice => 'Quick tag was successfully created.') }
        format.xml  { render :xml => @quick_tag, :status => :created, :location => @quick_tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quick_tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quick_tags/1
  # PUT /quick_tags/1.xml
  def update
    @quick_tag = QuickTag.find(params[:id])

    respond_to do |format|
      if @quick_tag.update_attributes(params[:quick_tag])
        format.html { redirect_to(quick_tags_path)}
		#format.html { redirect_to(@quick_tag, :notice => 'Quick tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quick_tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quick_tags/1
  # DELETE /quick_tags/1.xml
  def destroy
    @quick_tag = QuickTag.find(params[:id])
    @quick_tag.destroy

    respond_to do |format|
      format.html { redirect_to(quick_tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/quick_tags_helper.rb
module QuickTagsHelper
end

app/views/quick_tags/_form.html.erb
<%= form_for(@quick_tag) do |f| %>
  <% if @quick_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quick_tag.errors.count, "error") %> prohibited this quick_tag from being saved:</h2>

      <ul>
      <% @quick_tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quick_tags/edit.html.erb
    <div id="content">
    	<div id="interior">
		
		<%= form_for(@quick_tag) do |f| %>
  			<% if @quick_tag.errors.any? %>
    			<div id="error_explanation">
      				<h2><%= pluralize(@quick_tag.errors.count, "error") %> prohibited this quick_tag from being saved:</h2>
				    <ul>
      					<% @quick_tag.errors.full_messages.each do |msg| %>
        					<li><%= msg %></li>
      					<% end %>
				    </ul>
    			</div>
  			<% end %>
			<fieldset>
			<ul class="pageitem">
				<li class="bigfield">
					<!--<input placeholder="Title" type="text" />-->
					<%= f.text_field :title, :placeholder => "Title" %>
				</li>
			</ul>
			<ul class="pageitem">
				<li class="bigfield">
					<!--<input placeholder="Category" type="text" />-->
					<%= f.text_field :category, :placeholder => "Category" %>
				</li>
			</ul>
			<ul class="pageitem">
				<li class="checkbox">
					<span class="name">Location</span>
						<!--<input name="location" type="checkbox" id="edit_quick_tag" unchecked="true" />-->
						<% if @quick_tag.location == 0 %>
							<%= f.check_box :location, :unchecked => true %>
						<% end %>
						<% if @quick_tag.location == 1 %>
							<%= f.check_box :location, :checked => true %>
						<% end %>
				</li>
			</ul>
			<ul class="pageitem">
				<li class="button">
					<!--<input name="Submit" type="submit" value="UPDATE" class="orange" />-->
					<%= f.submit :value => "UPDATE", :class => "orange" %>
				</li>
			</ul>
			<ul class="pageitem">
						<li class="button">
							<%= button_to 'DESTROY', @quick_tag, :onclick => "return confirm('Are you sure you want to delete?')", :method => :delete, :class => "orange" %>
						</li>
			</ul>
		<% end %>
		</fieldset>
        </div><!--close interior-->
    </div><!--close content-->

app/views/quick_tags/index.html.erb
	<div id="content">
    	<div id="interior">
			<div style="text-align: center; padding-bottom: 10px;">
        		<span style="font-family: Helvetica, sans-serif; font-size: 18px;">
					<a href="<%= new_quick_tag_path %>" style="color: #ff6600; text-decoration: none;">+ Add</a> 
					<!--<span class="name">Edit
						<input name="location" type="checkbox" id="edit_quick_tag" unchecked="true" />
					</span>-->
            </div>
			<% if current_user.quick_tags == [] %>
				<ul class="pageitem">
	                <li class="quick-tag">
						<span class="title">No quick tags loaded</span>
					</li>
				</ul>
			<% else %>
				<% flag = "" %>
				<% @quick_tags.each_cons(2) do |quick_tag, next_quick_tag| %>
					<% if flag != quick_tag.category.downcase %>
						<span class="quickgroup" onclick = "$('#<%= quick_tag.category %>').toggle('slow');"><%= quick_tag.category %></span>
		        	    <ul class="pageitem" id="<%= quick_tag.category %>">
					<% end %>
		        	        <li class="quick-tag" id="<%= quick_tag.id %>" >
								<% if quick_tag.location == 1 %>
									<span class="title quicktag" id="<%= quick_tag.id %>"><%= quick_tag.title %>
										<img class="location-arrow" src="/images/location.png" />
									</span>
								<% elsif quick_tag.location == 0 %>
									<span class="title quicktag" id="<%= quick_tag.id %>"><%= quick_tag.title %></span>
								<% end %>
								<div id="quick_button<%= quick_tag.id %>" style="float: right; position: relative; top: -25px; padding-right: 5px; display: none;">
									<a href="/quick_tags/<%= quick_tag.id %>/edit"><img src="/images/edit.jpg" /></a>
								</div>
							</li>
					<% if next_quick_tag.category.downcase != quick_tag.category.downcase %>
						</ul>
					<% end %>
					<% flag = quick_tag.category.downcase %>
				<% end %>
			<% end %>
			<input type="hidden" id="tag_location" />
			
		</div><!--close interior-->
    </div><!--close content-->

<script>

	function initialize(){
		return true;
	}
	
	$(".quicktag").click(function(){
		/*if (document.getElementById("edit_quick_tag").checked)
		{
			// Load edit page for specific quick tag	
			window.location.replace("<%= root_url %>quick_tags/"+$(this).attr("id")+"/edit");
		}*/
		if (true)
		{	
			var position = $("#tag_location").val();
			$.ajax({
				beforeSend: function(xhr) {
    				xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
  				},
				url: "/new_quicktag",
				data: { user_id: <%= current_user.id %>, id: $(this).attr("id"), location: position },
				dataType: 'script',
				type: 'POST'
			});
			return true;
		}
	});
	
	function showMap(position) {
      		// Show a map centered at (position.coords.latitude, position.coords.longitude).
			document.getElementById("tag_location").value = position.coords.latitude+","+position.coords.longitude;
	}
	
	// One-shot position request.
	navigator.geolocation.getCurrentPosition(showMap);
</script>

		

app/views/quick_tags/new.html.erb
<div id="wrapper">
	<div id="header">
		<h1>Add Quick Tag</h1>
        <a href="<%= root_url %>" class="back"><img src="/images/back.png" alt="Back" /></a>
    </div><!--close header-->
    <div id="content">
    	<div id="interior">
			<%= form_for(@quick_tag) do |f| %>
  				<% if @quick_tag.errors.any? %>
  					<div id="error_explanation">
      					<h2>
							<%= pluralize(@quick_tag.errors.count, "error") %> prohibited this quick_tag from being saved:
						</h2>
					    <ul>
      						<% @quick_tag.errors.full_messages.each do |msg| %>
        						<li>
									<%= msg %>
								</li>
      						<% end %>
				      	</ul>
    				</div>
  				<% end %>
				
				<fieldset>
					<ul class="pageitem">
						<li class="bigfield">
							<%= f.text_field :title, :placeholder => "Title" %>
						</li>
					</ul>
					<ul class="pageitem">
						<li class="bigfield">
							<%= f.text_field :category, :placeholder => "Category" %>
						</li>
					</ul>
					<ul class="pageitem">
			            <li class="checkbox"><span class="name">Location</span>
							<!--<input name="location" type="checkbox" />-->
							<%= f.check_box :location %>
						</li>
					</ul>
					<ul class="pageitem">
						<li class="button">
							<%= f.submit :value => "SUBMIT", :class => "orange" %>
						</li>
					</ul>
					<div id="user_id">
						<%= f.text_field :user_id, :value => current_user.id %>
					</div>
				</fieldset>
			<% end %>
        </div><!--close interior-->
    </div><!--close content-->
    <div id="footer">
    	<p>&copy; copyright 2012 Tag Lab</p>
    </div><!--close footer-->
</div><!--close wrapper--> 

<!--<%= link_to 'Back', quick_tags_path %>-->

app/views/quick_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @quick_tag.title %>
</p>

<p>
  <b>Category:</b>
  <%= @quick_tag.category %>
</p>

<p>
  <b>Location:</b>
  <%= @quick_tag.location %>
</p>


<%= link_to 'Edit', edit_quick_tag_path(@quick_tag) %> |
<%= link_to 'Back', quick_tags_path %>